### ISSUE TITLE
Troubleshooting page has in-content Table of Contents code.

### ISSUE THREAD

**Issue by james-munson** [longhorn/website-docusaurus#36]
[Troubleshooting Problems](https://main--longhornio-docusaurus.netlify.app/docs/troubleshoot/troubleshooting) page still has redundant in-page ToC (and two copies of it!).  It looks like it is there for some versions and not others.

**Comment by jhkrug** [comment]
Thanks! Invetigating.

**Comment by jhkrug** [comment]
Fixed. In #37 

Thanks!
